feat(antrea): better docs for encyrption
replicatedhq/kurl.sh pull request #668
Opened 2022-01-25 18:33 UTC by DanStough

2022-01-25 20:20 UTC, ajp-io submitted a review, later dismissed

2022-01-25 21:00 UTC, ajp-io commented
@replicatedhq/replicated-docs For your reivew.

2022-01-25 21:59 UTC, samantha-replicated commented on src/markdown-pages/add-ons/antrea.md
> +An installer will block if encryption is enabled and the host does not have the required `wireguard` module installed.
```suggestion
An installer is blocked if encryption is enabled and the host does not have the required `wireguard` module installed.
```

2022-01-25 22:03 UTC, samantha-replicated commented on src/markdown-pages/add-ons/antrea.md
> +Disabling encryption by setting `isEncryptionDisabled` to `true` prevents the need to manually install `wireguard`.
```suggestion
If you do not want to install `wireguard` manually, you can disable encryption by setting `isEncryptionDisabled` to `true`. 
```

2022-01-25 22:05 UTC, samantha-replicated requested changes
Hi @DanStough. I added a couple edits. Just wanted you to review them first before committing to ensure I didn't impact the technical accuracy.

2022-01-26 01:41 UTC, ajp-io commented
> Hi @DanStough. I added a couple edits. Just wanted you to review them first before committing to ensure I didn't impact the technical accuracy.

Thanks, those edits look fine to me. I committed them.

2022-01-26 13:31 UTC, samantha-replicated approved these changes

2022-01-26 13:31 UTC, samantha-replicated commented
Approved. You can merge when you're ready :)

2022-01-26 13:39 UTC, merged