Add bugsnag to kurl.sh
replicatedhq/kurl.sh pull request #859
Opened 2022-09-08 03:56 UTC by jala-dx

#### What this PR does / why we need it:
Adds bugsnag to kurl.sh

#### Which issue(s) this PR fixes:
https://app.shortcut.com/replicated/story/57005/add-bugsnag-to-kurl-sh

#### Special notes for your reviewer:
Please refer to the above linked story.

#### Does this PR introduce a user-facing change?
No

#### Does this PR require documentation?
No

2022-09-08 22:47 UTC, jala-dx commented on .env.development
> +BUGSNAG_API_KEY="d9853b1ecad8ac8750308fe7ce9335b8"
github is odd?, there is no newline between 8 and 9.

2022-09-08 22:50 UTC, jala-dx commented on gatsby-browser.js
> +  apiKey: 'd9853b1ecad8ac8750308fe7ce9335b8',
need to fix this.

2022-09-08 23:05 UTC, emosbaugh requested changes
I think you need to set the release stage unless this is somehow set by gatsby automatically https://docs.bugsnag.com/platforms/go/other/configuration-options/#releasestage

2022-09-09 00:30 UTC, emosbaugh approved these changes

2022-09-09 00:32 UTC, jala-dx commented
> I think you need to set the release stage unless this is somehow set by gatsby automatically https://docs.bugsnag.com/platforms/go/other/configuration-options/#releasestage

yes you are right. We need to set the `release stages` and also `notifyReleaseStages` so that the notifications actually reach on  prod and staging.

2022-09-09 00:33 UTC, merged