document weave-to-flannel migration
replicatedhq/kurl.sh pull request #928
Opened 2023-01-18 22:27 UTC by laverya

2023-01-18 22:29 UTC, emosbaugh requested changes

2023-01-18 22:29 UTC, emosbaugh commented on src/markdown-pages/add-ons/flannel.md
> +	curl -fsSL https://kurl.sh/version/<version>/<installer>/tasks.sh | | sudo bash -s weave-to-flannel-secondary
```suggestion
	curl -fsSL https://kurl.sh/version/<version>/<installer>/tasks.sh | sudo bash -s weave-to-flannel-secondary
```

2023-01-18 22:56 UTC, laverya commented on src/markdown-pages/add-ons/flannel.md
> +	curl -fsSL https://kurl.sh/version/<version>/<installer>/tasks.sh | | sudo bash -s weave-to-flannel-secondary
🤦‍♂️

2023-01-19 00:09 UTC, emosbaugh submitted a review, later dismissed

2023-01-19 22:17 UTC, jonquil2002 submitted a review, later dismissed
lgtm - made some changes to conform with style guidelines.

2023-02-09 21:59 UTC, rrpolanco approved these changes

2023-02-09 22:08 UTC, merged