Update system-requirements.md to add support for Rocky 9.2
replicatedhq/kurl.sh pull request #978
Opened 2023-05-22 19:30 UTC by camilamacedo86

2023-05-22 22:22 UTC, emosbaugh requested changes

2023-05-22 22:22 UTC, emosbaugh commented on src/markdown-pages/install-with-kurl/system-requirements.md
>  * RHEL 7.4<sup>\*</sup>, 7.5<sup>\*</sup>, 7.6<sup>\*</sup>, 7.7<sup>\*</sup>, 7.8<sup>\*</sup>, 7.9, 8.0<sup>\*</sup>, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 9.0, 9.1 (RHEL 8.x and 9.x require Container
This should include support for RHEL 9.2

2023-05-23 01:48 UTC, emosbaugh approved these changes

2023-05-25 07:39 UTC, ricardomaraschini approved these changes

2023-05-25 09:21 UTC, merged